### ISSUE TITLE
Image dimensions larger than width: 800+ disappears in editor

### ISSUE THREAD

**Issue by funk101** [editor-js/image#101]
What I've noticed is that if the image width is too big, say over 800px, the editor displays a thumbnail then the image disappears.
It happens at the browser level, not in my upload script. The image gets put in the correct "uploads/" directory but the browser refreshes and all data is lost. I've been at this for weeks. Any ideas?

**Comment by neSpecc** [comment]
Can you provide a reproducible demo page?

**Comment by funk101** [comment]
working on it

**Comment by funk101** [comment]
Well, I made a build (react, express, etc), posted it to my server and it "seems" to be working. I'm pretty sure it has to do with "hot reloading" when using local dev server. The directory uploading to is "watched" by webpack. Even though I've put that directory on the ignore list it's intermittent only on larger width files. Anybody have experience with this situation?
