### ISSUE TITLE
How to upload file from device?

### ISSUE THREAD

**Issue by skumar606** [editor-js/image#107]
I am trying to save image data sent by the image tool to the backend. My post route looks like below
```
router.post('/editorJS/uploads',  (req, res) => {
    let b = req.body;
    let arrayBuffer = b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength);
    var bufferStream = new stream.PassThrough();
    // Write your buffer
    bufferStream.end(Buffer.from(b));
    (async () => {
        console.log(await FileType.fromStream(bufferStream));
    }
    )();
});
```

But the file type is `undefined`. I am not sure that req.body contains image or not. How can I get image data properly?

**Comment by neSpecc** [comment]
Need more details about your stack. Anyway, it is not related to the plugin, so I'll close the issue.
