### ISSUE TITLE
Add event on delete image

### ISSUE THREAD

**Issue by RetaxMaster** [editor-js/image#119]
This tool upload the image on my server when it is inserted (Would be better if the image comes in the JSON of the editor data), the problem is, if the user deletes the image from the editor i don't have any way to delete it from my server too, or is there some way to do this?

**Comment by Aayushpatil77** [comment]
Did find a way to do that??

**Comment by RetaxMaster** [comment]
Not yet, I would choose to perform a cronjob that determines which resources are being used and which are not

**Comment by Aayushpatil77** [comment]
Isn't their a simple way to do that?

**Comment by RetaxMaster** [comment]
I don't know, probably yo can hardcode the editor and the intercept the input file to detect changes and handle the event, but you must check the element classname into the editor to do that

**Comment by Aayushpatil77** [comment]
Yeah I implemented something like that

**Comment by aberba** [comment]
Image delete action is very much needed guys.

**Comment by neSpecc** [comment]
Duplicated #27
