### ISSUE TITLE
How can I send CSRF token with the image data?

### ISSUE THREAD

**Issue by Aayushpatil77** [editor-js/image#122]

**Comment by neSpecc** [comment]
You can use the `additionalRequestHeaders` or `additionalRequestData` properties of the [config](https://github.com/editor-js/image#config-params).

**Comment by Aayushpatil77** [comment]
I have another issue when I upload it to the backed it is giving me a error Image Tool: Invalid Response what can I do for that

**Comment by neSpecc** [comment]
Make sure your response format fits the [required format](https://github.com/editor-js/image#backend-response-format-)

**Comment by Aayushpatil77** [comment]
Thanks work like charm
