### ISSUE TITLE
How to determine if a image is deleted ?

### ISSUE THREAD

**Issue by Aayushpatil77** [editor-js/image#123]
The image gets uploaded to the backend if the user delete the image then how can we determine that

**Comment by aberba** [comment]
Exactly, would like to know when action to register for image delete/remove action in the Editor.

**Comment by moazam1** [comment]
I think when you get the generated blocks you can then compare with previously generated blocks, get the difference and figure out what's removed or added.

**Comment by albertri87** [comment]
I did same as @moazam1 but in future probably i create custon action copy as delete default action and request to server to delete image.

It will be interesting that image editor will implement delete method to request server instead create custom action

**Comment by artsur** [comment]
I determine that when I save editor data. Just compare old and new data.
This is an PHP-function example for delete files of **Images** and **Attaches**:
```
function filesForDelete($old_data, $new_data){
        if(!is_array($old_data)){
            $old_data = json_decode($old_data,true);
        }
        if(!is_array($new_data)){
            $new_data = json_decode($new_data,true);
        }

        $old_files = [];
        $new_files = [];

        foreach($old_data as $block) {
            $block = json_decode(json_encode($block), FALSE);
            if($block->type == 'image'){
                $old_files[] = $block->data->file->url;
                $old_files[] = $block->data->file->original;
            }elseif($block->type == 'attaches'){
                $old_files[] = $block->data->file->url;
            }
        }
        foreach($new_data as $block) {
            $block = json_decode(json_encode($block), FALSE);
            if($block->type == 'image'){
                $new_files[] = $block->data->file->url;
                $new_files[] = $block->data->file->original;
            }elseif($block->type == 'attaches'){
                $new_files[] = $block->data->file->url;
            }
        }

        $for_delete = array_values(array_diff($old_files,$new_files));
       
        if(count($for_delete)>0){
            foreach($for_delete as $file_url){
                deleteFile($file_url);
            }
        }
    }
```
Where are:

`$old_data` - the last saved editor.js data from database;

`$new_data` - new editor.js data from request;

`deleteFile($file_url)` - some function to delete the file.

We pass url to it. So you need to convert url to file path.

**Comment by neSpecc** [comment]
Duplicate #27
