### ISSUE TITLE
Default tunes (moveUp, moveDown, delete) don't show up

### ISSUE THREAD

**Issue by NogaMan** [editor-js/image#138]
Hi!

The default tunes (moveUp, moveDown, delete) don't show up! I use:
 - **@editorjs/editorjs: ^2.20.1**
 - **@editorjs/image: ^2.6.0**

The custom actions like stretched and so on are showing up okay

**Comment by gohabereg** [comment]
Hi 
Please update to 2.20.2

**Comment by sicongzhao** [comment]
I got the same mistake on the latest version: @editorjs/editorjs@2.26.4
Can you help fix this? Thanks in advance.
