### ISSUE TITLE
Image Tool: uploading failed because of Object

### ISSUE THREAD

**Issue by AFireInside777** [editor-js/image#147]
I am using editor js and the image module with Javascript.
The image button appears on the editor on my page, however, it will not fully upload the photo.
I get the message "cannot upload an image. Try another."
In the console, I get the following message:

![Screenshot 2021-05-25 144925](https://user-images.githubusercontent.com/49132327/119552689-cab46300-bd68-11eb-92fe-0e996f2ff572.png)

I cannot find anywhere online that gives a solution to this issue.
Here is my code in the HTML body, please tell me what is going wrong:

```
<script>
    const ImageTool = window.ImageTool;
</script>

<script>
    const editor = new EditorJS({
        holder: 'editorjs',
        tools: {
            image: {
                class: ImageTool,
                config: {
                    endpoints: {
                        byFile: 'http://localhost:8008/uploadFile', // Your backend file uploader endpoint
                        byUrl: 'http://localhost:8008/fetchUrl', // Your endpoint that provides uploading by Url
                    }
                }
            }
        }
    })
</script>
```

**Comment by neSpecc** [comment]
Can you show your server response?

**Comment by 98sarthakjain** [comment]
SAME ISSUE!!!


```
@app.route("/upload-image", methods=["GET", "POST"])
def upload_image():
    if request.method == "POST":
        if request.files:
            image = request.files["image"]
            image.save(os.path.join(app.config["IMAGE_UPLOADS"], image.filename))
            print("Image saved")
            return jsonify({ "success" : 1,"file": {
        "url" : "https://www.tesla.com/tesla_theme/assets/img/_vehicle_redesign/roadster_and_semi/roadster/hero.jpg",
    }})
    return render_template("public/upload_image.html")
```



<>
JS
     image: {
       class: ImageTool,
       config: {
         endpoints: {
           byFile: 'http://127.0.0.1:5000/upload-image/', // Your backend file uploader endpoint
           byUrl: 'http://127.0.0.1:5000/upload-image/', // Your endpoint that provides uploading by Url
         }
       },

**Comment by neSpecc** [comment]
@AFireInside777 Looks like you're not implemented the backend side.

**Comment by neSpecc** [comment]
@98sarthakjain sorry, could not understand your message.

**Comment by haodev007** [comment]
> Can you show your server response?

Hi, What should return as response on backend side?

**Comment by 98sarthakjain** [comment]
Hey,
Thanks for the response, you can go ahead and close the ticket. It seems
with updates the issue was resolved at the time of query.

Thanks,
Sarthak Jain
Senior Product Developer

**Comment by Eyepatch5263** [comment]
@98sarthakjain well I've found the solution actually, see when you're using uploadByFile method you've to pass the res from the server as a certain format and that format is 
{
    "success" : 1,
    "file": {
        "url" : "https://www.tesla.com/tesla_theme/assets/img/_vehicle_redesign/roadster_and_semi/roadster/hero.jpg",
        // ... and any additional fields you want to store, such as width, height, color, extension, etc
    }
} is this one 
and for the uploadByUrl method: 
{
  "url": "<pasted URL from the user>"
  "additionalRequestData": "<additional request data from configuration>"
} this should be your responses from the sever 

scenario for uploadByFile from device is:
User select file from the device
Tool sends it to your backend (on config.endpoints.byFile route)
Your backend should save file and return file data with JSON at specified format.
Image tool shows saved image and stores server answer

scenario for uplaodByUrl is:

User pastes an URL of the image file to the Editor
Editor pass pasted string to the Image Tool
Tool sends it to your backend (on config.endpoints.byUrl route) via 'url' in request body
Your backend should accept URL, download and save the original file by passed URL and return file data with JSON at specified format.
Image tool shows saved image and stores server answer
