### ISSUE TITLE
How to remove Tunes like stretched or with background

### ISSUE THREAD

**Issue by SogoCZE** [editor-js/image#149]
Hello,

I would like to ask how to remove some special Tunes like stretched, with background, with border etc.

Thanks

![Remove There's](https://user-images.githubusercontent.com/8431593/120901721-da6f5980-c63c-11eb-8634-1c94c3155c2c.png)

**Comment by neSpecc** [comment]
You can fork and remove the `renderSettings` method 
https://github.com/editor-js/image/blob/master/src/index.js#L201

**Comment by SogoCZE** [comment]
Ok, thanks. 

Also I think it would be great if you provide some config options to disable some tunes.

**Comment by simpleoo0o** [comment]
import ImageTool from '@editorjs/image'
Object.defineProperty(ImageTool, 'tunes', {
  get: function() { return [] }
})

**Comment by ianmustafa** [comment]
For cleaner result that also conforms with TypeScript, ectends the ImageTool and override the `tunes` getter:

```typescript
import ImageTool from '@editorjs/image'

class CustomImageTool extends ImageTool {
  public static override get tunes(): [] {
    return []
  }
}

const editor = new EditorJS({
  tools: {
    image: {
      class: CustomImageTool,
      // additional configuration...
    },
  },
})
```

**Comment by neSpecc** [comment]
You can use `features` config option. See readme for details.
