### ISSUE TITLE
How do I override the device boot popup?

### ISSUE THREAD

**Issue by melishev** [editor-js/image#157]
I am writing a plugin for Headless Cms, based on Editor.js, all additional plugins to it started without problems, but at the moment I settled on this plugin. The CMS has its own plugin for uploading images, both from the server and from the device. How can I override windows so that when I add an image, I have a CMS window, and not the standard boot from the device?

> Russia
Я пишу плагин для Headless Cms, на основе Editor.js, все дополнительные к нему плагины запустились без проблем, но в данный момент я остановился на этом плагине. В CMS есть свой плагин загрузки изображений, как с сервера, так и с девайса. Как я могу переопределить окна, что бы при добавлении изображения у меня появлялось окно CMS, а не стандартное загрузки с устройства?

**Comment by neSpecc** [comment]
You can fork and override the `uploadSelectedFile` method https://github.com/editor-js/image/blob/master/src/uploader.js#L44-L70
