### ISSUE TITLE
Caption saving TypeError

### ISSUE THREAD

**Issue by katsumi-axis** [editor-js/image#179]
I get the following error when saving.
`Saving failed due to the Error TypeError: Cannot assign to read only property 'caption' of object '#<Object>'`

**Comment by gvete** [comment]
How did you close this? I am still having the issue
Saving failed due to the Error TypeError: Cannot assign to read only property 'caption' of object '#<Object>'
![image](https://user-images.githubusercontent.com/940168/227109057-1aaab467-738c-4faf-a14a-c085a5b3c0bf.png)
