### ISSUE TITLE
No request data when drag-and-drop or pasting image file

### ISSUE THREAD

**Issue by dellow** [editor-js/image#18]
When dragging and dropping an image on editor it fires the `byFile` endpoint but the request data on the backend side is empty.

Works fine when using the actual upload image button from the toolbar.

**Comment by gohabereg** [comment]
Hi @dellow !

Could you provide some code samples? 

Here is a working example on express.js:

https://github.com/codex-team/codex.docs/blob/master/src/routes/api/transport.js#L52
https://github.com/codex-team/codex.docs/blob/master/src/frontend/js/classes/editor.js#L48

**Comment by dellow** [comment]
Wasn't on latest version. Everything working as expected now. Closing issue.
