### ISSUE TITLE
Cool plugin, thanks

### ISSUE THREAD

**Issue by ivictbor** [editor-js/image#181]
One thing readme says

"This Tool is also capable of uploading & displaying video files using the"  ...

the what? =)

**Comment by gilluminate** [comment]
I had this same question. The readme file has an un-escaped `<video>` tag in it. If you look at the [raw README.md file](https://raw.githubusercontent.com/editor-js/image/master/README.md) instead, you'll see the rest of the sentence.

```
This Tool is also capable of uploading & displaying video files using the <video> element. To enable this, specify video mime-types via the 'types' config param.
```
