### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by gilluminate** [editor-js/image#193]
Lots of issues and PRs piling up that seem to be ignored. Is this project still being maintained?

**Comment by pruhstal** [comment]
@gilluminate Good question. It certainly appears so. There's of course the similar `simple-image` repo: https://github.com/editor-js/simple-image which adds to the fragmentation.

For features like https://github.com/editor-js/image/pull/53 that are pretty critical from an SEO standpoint, I'm convinced it's probably time to fork this. If so, I'll take the lead.

Would love some assistance with parsing through the current PRs to see which ones are worthy enough to make it in, as well.

**Comment by neSpecc** [comment]
Seems outdated
