### ISSUE TITLE
The plugin is not rendering the <img> tag after upload

### ISSUE THREAD

**Issue by rolfo85** [editor-js/image#21]
Hi,

I configured the image plugig and it's partially working. Basically after I upload an image, I get a never ending loader without the tag <img> with the url being created.

this is the image tool config:

    `image: {
          class: ImageTool,
               config: {
                    endpoints: {
                         byFile: '/api/images/image-handler' + '?api_token=' + this.isLogged.apiToken,
                    }
               }
     }`

This is the response from the backend (static url just for the example)

    `return response()->json([
            "success" => 1,
            "file" => "http://localhost:8000/storage/rte-images/rose-small.jpg",
     ]);`

and this is the `outputData` that I'm console logging `onChange`

`{
    file: "http://localhost:8000/storage/rte-images/rose-small.jpg",
    caption: "",
    withBorder: false,
    stretched: false,
    withBackground: false
}`

It's all correct. The image is properly added to the JSON with the url I'm passing in the response. And I get no errors of any kind. So it's actually working except for the fact that the image preloader keeps spinning forever and no <img> tag is added.

Maybe I miss something?

**Comment by neSpecc** [comment]
Hi. The `file` property is an object, not a string. It should contain at least an `url` property and may contain any additional fields got from your backend, such as `width`, `height`, `color` and other

**Comment by rolfo85** [comment]
Thank you very much. It's working now but it seems it doesn't get neither the caption I'm passing with the response nor the image styles properties.

This is the updated code of my response.

    `return response()->json([
            "success" => 1,
            "file" => [
                "url" => "http://localhost:8000/storage/rte-images/" . $cleanedFilenameWithExtension
            ],
            "caption" => "this is the caption",
            "withBorder" => false,
            "withBackground" => false,
            "stretched" => true
        ]);`

**Comment by neSpecc** [comment]
What about passing caption from backend, there is an issue for that.
