### ISSUE TITLE
Error: To enable read-only mode all connected tools should support it. Tools image don't support read-only mode.

### ISSUE THREAD

**Issue by ZTSS221** [editor-js/image#216]
Error: To enable read-only mode all connected tools should support it. Tools image don't support read-only mode.

**Comment by ZTSS221** [comment]
Error: To enable read-only mode all connected tools should support it. Tools image don't support read-only mode.

**Comment by tommygood** [comment]
Still have same issue.

**Comment by thecliffparis** [comment]
Same here. Issue is still live

**Comment by thecliffparis** [comment]
> This tool [supports](https://github.com/editor-js/image/blob/master/src/index.ts#L149) read-only.
> 
> Are you sure that you're using exactly this tool?

Using
`<script src="https://cdn.jsdelivr.net/npm/@editorjs/image@latest"></script>
... after editor ready ...
editor.readOnly.toggle();`

Error
`To enable read-only mode all connected tools should support it. Tools image don't support read-only mode.`

**Comment by neSpecc** [comment]
I can’t confirm that. I just checked, and it worked fine.

**Comment by thecliffparis** [comment]
> I can’t confirm that. I just checked, and it worked fine.

According to you, what should I change in my javascript code ?

**Comment by neSpecc** [comment]
show the `customTools` object

**Comment by thecliffparis** [comment]
> > > I can’t confirm that. I just checked, and it worked fine.
> > 
> > 
> > According to you, what should I change in my javascript code ?
> 
> show me the `customTools` object

```
const customTools = {
        refineinline: {
            class: RefineInline,
            config: {
                menuId: menu_id,
            }
        }, 
        paragraph: {
            class: Paragraph,
            config : {
                placeholder: 'Enter a text'
            },
            inlineToolbar: inlineToolbarConfig
        },
        header: {
            class: Header,
            config: {
                placeholder: 'Enter a title',
                levels: [1, 2, 3],
                defaultLevel: 2
            },
            inlineToolbar: inlineToolbarConfigHeader
        },
        image: {
            class: SimpleImage,
            config: {
                menuId: menu_id_image
            }
        }, 
        list: {
            class: EditorjsList,
            inlineToolbar: inlineToolbarConfig
        },
        table: {
            class: Table,
            toolbox: {
                title: '<div class="ce-popover-item__title">Table</div><div class="ce-popover-item__subtitle">Add tabular content</div>'
            }
        },
        underline: {
            class: CustomUnderline,
            inlineToolbar: true
        }
    };
```

**Comment by neSpecc** [comment]
First of all, you're passing `SimpleImage` which is [another tool](https://github.com/editor-js/simple-image). But it also support readonly. 

I'm not sure how it is working for you. 

This import 

```
<script src="https://cdn.jsdelivr.net/npm/@editorjs/image@latest"></script>
```

and this code

```
 image: {
            class: SimpleImage,
            config: {
                menuId: menu_id_image
            }
        }, 
```

should lead reference error about `Can't find variable: SimpleImage`.

**Comment by neSpecc** [comment]
Also, Simple Image does not have such a config:

```
config: {
  menuId: menu_id_image
}
```

so, you're probably using some 3rd party or own tool

**Comment by thecliffparis** [comment]
> Also, Simple Image does not have such a config:
> 
> ```
> config: {
>   menuId: menu_id_image
> }
> ```
> 
> so, you're probably using some 3rd party or own tool

Checking now.

**Comment by thecliffparis** [comment]
> First of all, you're passing `SimpleImage` which is [another tool](https://github.com/editor-js/simple-image). But it also supports readonly.
> 
> I'm not sure how it is working for you.
> 
> This import
> 
> ```
> <script src="https://cdn.jsdelivr.net/npm/@editorjs/image@latest"></script>
> ```
> 
> and this code
> 
> ```
>  image: {
>             class: SimpleImage,
>             config: {
>                 menuId: menu_id_image
>             }
>         }, 
> ```
> 
> should lead reference error about `Can't find variable: SimpleImage`.

Thank you for the feedback.
I just replaced SimpleImage to Image but I still have the same error in the console

```
  image: {
             class: Image,
             config: {
                 menuId: menu_id_image
             }
         }, 
```

**Comment by neSpecc** [comment]
I suppose that you're looking on a wrong code. `Image` is a native js class. Image tool export `ImageTool` class.

**Comment by thecliffparis** [comment]
> I suppose that you're looking on a wrong code. `Image` is a native js class. Image tool export `ImageTool` class.

My bad, you are right. Moved from SimpleImage to ImageTool.

The error is still the same.
The overall error message

```
To enable read-only mode all connected tools should support it. Tools image don't support read-only mode.
    at os.throwCriticalError (https://cdn.jsdelivr.net/npm/@editorjs/editorjs@latest:43:19127)
    at os.toggle (https://cdn.jsdelivr.net/npm/@editorjs/editorjs@latest:43:18629)
    at Wo.toggle (https://cdn.jsdelivr.net/npm/@editorjs/editorjs@latest:26:3151)
    at Object.toggle (https://cdn.jsdelivr.net/npm/@editorjs/editorjs@latest:26:3074)
```

**Comment by neSpecc** [comment]
> I suppose that you're looking on a wrong code. Image is a native js class. Image tool export ImageTool class.

That means that you're showing code that is not being executed. Find the right code and there will be another image tool

**Comment by thecliffparis** [comment]
> > I suppose that you're looking on a wrong code. Image is a native js class. Image tool export ImageTool class.
> 
> That means that you're showing code that is not being executed. Find the right code and there will be another image tool

That is the only code running... I updated with a console log to make sure of it.

```
class ImageTool {
        constructor({api, config, data}) {
            this.api = api;
            this.config = config || {};

            this.wrapper = undefined;

            this.data = {
                url: data.url || null,
                caption: data.caption || null,
                withBorder: data.withBorder !== undefined ? data.withBorder : false,
                withBackground: data.withBackground !== undefined ? data.withBackground : false,
                stretched: data.stretched !== undefined ? data.stretched : false,
            };
    
            console.log("constructor url is "+data.url);
        }
}
```

**Comment by neSpecc** [comment]
So there is your own ImageTool ?

**Comment by thecliffparis** [comment]
> So there is your own ImageTool ?

I see... I should have extends the class
