### ISSUE TITLE
Can't get the caption and the image styles from response

### ISSUE THREAD

**Issue by rolfo85** [editor-js/image#22]
It seems it doesn't get neither the caption nor the image style properties (stretched, withBackground, withBorder) that I'm passing with the response.

This is the code of my response.

       return response()->json([

            "success" => 1,

            "file" => [

                "url" => "http://localhost:8000/storage/rte-images/" . $cleanedFilenameWithExtension
            ],

            "caption" => "this is the caption",

            "withBorder" => false,

            "withBackground" => false,

            "stretched" => true

        ]);`

When I look into the outputData, the caption is always an empty string and the image properties (stretched, withBackground, withBorder) are all false.

**Comment by neSpecc** [comment]
For now `caption`, `withBorder`, `withBackground` and `stretched` is the properties that can be set only via Editor's UI. Backend response should only contain `success` and `file` fields, as describes in [plugins docs](https://github.com/editor-js/image#uploading-files-from-device-).
