### ISSUE TITLE
Option to remove caption and extra features (border, stretch, etc.)

### ISSUE THREAD

**Issue by collimarco** [editor-js/image#236]
Is there any way to disable the caption and the extra features?

Basically we do not want to display the caption input because we don't need it for our application.

Also we do not need the extra features (border, stretch, etc.).

Is there any way to disable all this and have only an upload to the server of a simple image?

Thanks

**Comment by collimarco** [comment]
I see that my suggestion is already implemented by this pull request (which has many upvotes):

https://github.com/editor-js/image/pull/96

It would be great if someone could merge it.

**Comment by idebenone** [comment]
Closing this as it has been added in #269.
