### ISSUE TITLE
Allow to execute a function when File is uploaded, along with passing the Values...

### ISSUE THREAD

**Issue by prashant1k99** [editor-js/image#24]
I think it would be great if you just allow the **calling a function** passing the image data as parameter and then will use it to send to backend with custom configs (if the user wants to edit some config). That will make it more efficient for developers to use it...

**Comment by neSpecc** [comment]
@prashant1k99 before uploading or after?

**Comment by prashant1k99** [comment]
> @prashant1k99 before uploading or after?

Before uploading...

**Comment by neSpecc** [comment]
@prashant1k99 the feature will be ready soon. See implementation at #26
