### ISSUE TITLE
The block can not be displayed correctly.

### ISSUE THREAD

**Issue by KariMuhammad** [editor-js/image#261]
When I render these blocks of content by this code, it gives me the Error **The block can not be displayed correctly.**
how to solve this problem?

#### Blocks of Content
![image](https://github.com/user-attachments/assets/f2be703b-f253-40b2-bd36-5e8807aff431)

#### Code
![image](https://github.com/user-attachments/assets/f2d80657-c3b7-4335-b94d-eb318f8e2dca)

#### Error
![image](https://github.com/user-attachments/assets/695a62a4-1c27-4717-8952-a417aeb07919)

**Comment by neSpecc** [comment]
There is likely some error thrown during render a block. Could you share console logs? Also, you're using an old version of editor and it is recommended to update

**Comment by KariMuhammad** [comment]
Sorry, The problem was in my code, i should set `tools` property for editor instance to render the appropriate blocks, so i set Image tool and it worked.

Thanks for speed respond @neSpecc, and sorry for my late :(
