### ISSUE TITLE
Same Image gets rendered into all the proceeding image blocks.

### ISSUE THREAD

**Issue by utkarshrai003** [editor-js/image#51]
I am trying to upload an image using the `config.endpoints` function. The very first image I upload is correct, but rest other images following it are the same as the first one. Although, the back end is returning correct URL for the newly update image.

My configuration is as follows - 

```
tools: {
        image: {
          class: ImageTool,
          config: {
            endpoints: {
              byFile: 'http://localhost:3001/api/v1/file_upload'
            },
            field: 'file',
            types: 'image/*',
          }
        }
```

**Comment by galacticor** [comment]
Hi, i have the same problem here. Could you please tell me how i resolve this, please help

**Comment by galacticor** [comment]
> I am trying to upload an image using the `config.endpoints` function. The very first image I upload is correct, but rest other images following it are the same as the first one. Although, the back end is returning correct URL for the newly update image.
> 
> My configuration is as follows -
> 
> ```
> tools: {
>         image: {
>           class: ImageTool,
>           config: {
>             endpoints: {
>               byFile: 'http://localhost:3001/api/v1/file_upload'
>             },
>             field: 'file',
>             types: 'image/*',
>           }
>         }
> ```

Hi, i have the same problem here. Could you please tell me how i resolve this, please help

**Comment by quard8** [comment]
@galacticor check your backend implementation for file upload. I had similar problem and apparently my backend was saving images with same name

**Comment by galacticor** [comment]
@quard8 Hi, thanks for your reply. My backend give some random string and timestamp at end of image file. But, I still dont know whats wrong
