### ISSUE TITLE
Passing the data into editor ignore stretched image

### ISSUE THREAD

**Issue by MrSimmmons** [editor-js/image#55]
If you want to pass the data from editor JS into the `data:` value of the editor config, it ignores the stretched value. Im guessing that this is an issue with the render function of this module, rather than an issue with the main editor JS API

See CodePen: https://codepen.io/MrSimmons/pen/QWWYVvy
If you change the boolean of stretched in the data, you can see that the image doesn't resize in the editor. the image in the editor only resizes when you then toggle the stretched value off then on again in the editor.

**Comment by CyborgSemon** [comment]
Update: It seems that it applies the full with to the block above it if there is one.

**Comment by OneLoneFox** [comment]
Sad this issue never got attention It's still present to this day, loading any image with stretched set to true leaves the image unstretched and stretches the block above it
