### ISSUE TITLE
Where is the file data during request to server?

### ISSUE THREAD

**Issue by avillarubia** [editor-js/image#62]
Good day guys,

I have a summary of my concern below

```
const EDITOR_JS_TOOLS = {
    image: {
        class: Image,
        config: {
            endpoints: {
                byFile: 'http://localhost:3001/api/uploads'
            },
            field: 'image',
            types: 'image/*'
        }
    }
}

const CommentEditor = () => {
    return <EditorJs tools={EDITOR_JS_TOOLS} />
}
```

When my react sends request to

```
router.post('/', async (req, res) => {
//when client use this endpoint, console.log can display a message
})
```

but where is the data?
I look it to req.body but empty

Thank you.

**Comment by dmitriymnv** [comment]
Try using the "multer" library [https://github.com/expressjs/multer](url)

**Comment by neSpecc** [comment]
Yes, looks like you've missed the file accepting middleware in your nodejs app. 

There is an example of the simplest backend implementation: https://github.com/editor-js/image/blob/master/dev/server.js
