### ISSUE TITLE
How to Save image backend PHP

### ISSUE THREAD

**Issue by tojobbws** [editor-js/image#88]
I have followed the example but cannot work.

```
const editor = new EditorJS({
		autofocus: true,
		tools: {
			embed: Embed,
			image: {
				class: ImageTool,
				config: {
					endpoints: {
						byFile: 'http://localhost/editor/uploadfile.php' // Your backend file uploader endpoint
						
					}
				}
			}
		}
    });
```

In uploadfile.php

`<?php
print_r($_FILE);
?>`

**Comment by kaaaaaaaaaaai** [comment]
is typo? `$_FILES`

**Comment by tojobbws** [comment]
Thank you
I forgot S
$_FILE > $_FILES
> is typo? `$_FILES`

**Comment by kaaaaaaaaaaai** [comment]
np.
im glad the problem is solve. ^-^b

could you close this issue if there are not any problems.

**Comment by leonsegal** [comment]
How would you access the file in node.js? When I log req.body it is just an empty object e.g. `{}`.
