### ISSUE TITLE
There is no ability to configure "inlineToolbar" option.

### ISSUE THREAD

**Issue by proArtex** [editor-js/image#9]
Inline toolbar icon is hardcoded, but I want to upload file by paste-action only (by url/file).

**Comment by gohabereg** [comment]
Hi @proArtex,

Do you mean toolbox icon?
Toolbox icon can be overridden by passing `toolbox` property to tool's config

```
new CodeXEditor({
  tools: {
    image: {
      class: Image,
      toolbox: {
        icon: null
      }
    }
  }
})
```

**Comment by proArtex** [comment]
@gohabereg it doesn't change anything actually.
editor: 2.7.22
image: 2.0.2

**Comment by neSpecc** [comment]
Outdated issue
