### ISSUE TITLE
How to save the image in node js

### ISSUE THREAD

**Issue by leonsegal** [editor-js/image#93]
How do you access the file in node.js? When I log req.body it is just an empty object e.g. {}.

**Comment by neSpecc** [comment]
You need to use some kind of middleware to access form-data. For example, [formidable](https://github.com/node-formidable/formidable). See an example at our testing uploader: https://github.com/editor-js/image/blob/master/dev/server.js#L145

**Comment by leonsegal** [comment]
Just to clarify - did you mean at the point where the image plugin makes a request to the backend node server (which sends a response which includes the file url)? 

Or did you mean at the point of submission?

I was asking about the former.

**Comment by neSpecc** [comment]
>  did you mean at the point where the image plugin makes a request to the backend node server

yes, I mean the backend implementation
